name: CI Python Application

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  app-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Python App
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.run_number }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.run_number }}

      - name: Update Terraform Script
        run: |
          cd terraform
          sed -i "s|\(default\s*=\s*\"\)[^\"]\+\(\"\)|\1${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.run_number }}\2|" variables.tf
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add variables.tf
          git commit -m "Update variables.tf"
          git push
